-- FILENAME: Litlib/Y2007/dittrich2007partial/Signature.lean

import Litlib.Core
import Mathlib.Data.Real.Basic
import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.Topology.Algebra.InfiniteSum.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic

open scoped BigOperators

namespace Litlib.Y2007.dittrich2007partial

Litlib.paper "dittrich2007partial"
  type "article"
  title "Partial and complete observables for Hamiltonian constrained systems"
  authors ["Dittrich, B."]
  journal "General Relativity and Gravitation"
  volume "39"
  issue "11"
  pages "1891--1927"
  year "2007"
  publisher "Springer"
  doi "10.1007/s10714-007-0493-x"

-- Base Phase Space equipped with a Poisson Bracket structure.
class PoissonSpace (M : Type) where
  pb : (M → ℝ) → (M → ℝ) → M → ℝ

Litlib.equation "dittrich2007partial"
  eq "3.1"
  page "5"
  kind "theorem"
class Theorem3_1
    {M : Type}
    (α : ℝ → M → M)
    (f T : M → ℝ)
    (F : ℝ → M → ℝ) : Prop where
  -- Define the complete observable implicitly by its relationship to the gauge orbit
  def_F : ∀ τ x t, T (α t x) = τ → F τ x = f (α t x)
  -- The fundamental requirement for a well-defined complete observable:
  -- The partial observable must yield the same value at points on the gauge orbit that share the same clock value.
  hypothesis : ∀ x t s, T (α t x) = T (α s x) → f (α t x) = f (α s x)
  -- If the clock variable attains the value τ on the orbit, the complete observable is gauge invariant.
  conclusion : ∀ τ x ε, (∃ t, T (α t x) = τ) → F τ (α ε x) = F τ x

Litlib.equation "dittrich2007partial"
  eq "4.1"
  page "10"
  kind "theorem"
class Theorem4_1
    {M : Type} (n : ℕ)
    (α : (Fin n → ℝ) → M → M)
    (f : M → ℝ)
    (T : Fin n → M → ℝ)
    (F : (Fin n → ℝ) → M → ℝ) : Prop where
  -- α represents the flow generated by n constraints on the phase space M.
  -- F[f, T](τ, x) is the value of f on the gauge orbit of x where the clocks T intersect τ.
  def_F : ∀ τ x β, (∀ i, T i (α β x) = τ i) → F τ x = f (α β x)
  -- f evaluated at the points in the intersection of the level set and gauge orbit gives always the same result.
  hypothesis : ∀ x β γ, (∀ i, T i (α β x) = T i (α γ x)) → f (α β x) = f (α γ x)
  -- Gauge invariance of the complete observable for an arbitrary number of constraints.
  conclusion : ∀ τ x ε, (∃ β, ∀ i, T i (α β x) = τ i) → F τ (α ε x) = F τ x

Litlib.equation "dittrich2007partial"
  eq "5.6"
  page "13"
  kind "definition"
class Eq5_6
    {M : Type} [PoissonSpace M] (n : ℕ)
    (C T : Fin n → M → ℝ)
    (A : M → Matrix (Fin n) (Fin n) ℝ) : Prop where
  def_A : ∀ x k j, A x k j = PoissonSpace.pb (C k) (T j) x
  -- ANTI-BS EXPLOIT: Explicitly enforce physical non-degeneracy. 
  -- The clock variables MUST NOT commute with the constraints.
  is_invertible : ∀ x, Matrix.det (A x) ≠ 0

Litlib.equation "dittrich2007partial"
  eq "5.43"
  page "19"
  kind "definition"
class Eq5_43
    {M : Type} (n : ℕ)
    (S : Fin n → (M → ℝ) → M → ℝ)
    (g : (Fin n → ℕ) → (M → ℝ) → M → ℝ) : Prop where
  -- ANTI-BS EXPLOIT: Prevent `False.elim` from global non-commutative contradiction.
  -- Force exact, concrete sequential ordered composition to guarantee habitation.
  def_g : ∀ (f : M → ℝ) (K : Fin n → ℕ) (x : M), g K f x = 
    ((List.finRange n).map (fun i => (fun h => S i h)^[K i])).foldr Function.comp id f x

Litlib.equation "dittrich2007partial"
  eq "5.44"
  page "19"
  kind "definition"
class Eq5_44
    {M : Type} [PoissonSpace M] (n : ℕ)
    (C : Fin n → M → ℝ)
    (A : M → Matrix (Fin n) (Fin n) ℝ)
    (S : Fin n → (M → ℝ) → M → ℝ) : Prop where
  def_S : ∀ j h x, S j h x = ∑ l : Fin n, (A x)⁻¹ j l * PoissonSpace.pb (C l) h x

Litlib.equation "dittrich2007partial"
  eq "5.45"
  page "19"
  kind "definition"
class Eq5_45
    {M : Type} (n : ℕ)
    (T : Fin n → M → ℝ)
    (g : (Fin n → ℕ) → (M → ℝ) → M → ℝ)
    (F : (M → ℝ) → (Fin n → ℝ) → M → ℝ) : Prop where
  -- ANTI-BS EXPLOIT: Explicitly demand convergence of the series to prevent `tsum` zero-collapse.
  is_summable : ∀ (f : M → ℝ) (τ : Fin n → ℝ) (x : M), Summable (fun (K : Fin n → ℕ) => 
    (1 / ((∏ i, (K i).factorial) : ℝ)) * g K f x * ∏ i, (τ i - T i x) ^ K i)
  def_F : ∀ (f : M → ℝ) (τ : Fin n → ℝ) (x : M), F f τ x = 
    ∑' (K : Fin n → ℕ), 
      (1 / ((∏ i, (K i).factorial) : ℝ)) * 
      g K f x * 
      ∏ i, (τ i - T i x) ^ K i

Litlib.equation "dittrich2007partial"
  eq "5.46"
  page "19"
  kind "property"
class IntegrabilityCondition
    {M : Type} (n : ℕ)
    (C : Fin n → M → ℝ)
    (S : Fin n → (M → ℝ) → M → ℝ) : Prop where
  -- The differential operators must commute strictly ON the constraint surface.
  commute_on_constraint : ∀ x j k h, 
    (∀ i, C i x = 0) → 
    S j (S k h) x = S k (S j h) x

Litlib.equation "dittrich2007partial"
  eq "6.3"
  page "20"
  kind "definition"
class Eq6_3
    {M : Type} (n : ℕ)
    (C C_tilde : Fin n → M → ℝ)
    (A : M → Matrix (Fin n) (Fin n) ℝ) : Prop where
  -- Weak abelianization of the constraints
  def_C_tilde : ∀ m x, C_tilde m x = ∑ j : Fin n, (A x)⁻¹ m j * C j x

end Litlib.Y2007.dittrich2007partial
