-- FILENAME: Litlib/Y2003/nakahara2003geometry/Chapter11/Sec01_InvariantPolynomials.lean

import Litlib.Core
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Algebra.Algebra.Pi

namespace Litlib.Y2003.nakahara2003geometry

Litlib.equation "nakahara2003geometry" eq "11.7_post" kind "statement"
/--
The invariant polynomial `P` is explicitly restricted to belong to the
subring/algebra generated by the trace functions `A ↦ tr(A^r)`. Downstream
instantiations must construct it from traces of matrix powers.
-/
class Eq11_7_post
    (n : ℕ)
    (R : Type*) [CommRing R] [Algebra ℝ R]
    (tr : Matrix (Fin n) (Fin n) R → R)
    (isInvariant : (Matrix (Fin n) (Fin n) R → R) → Prop) where
  generated_by_traces :
    ∀ P, isInvariant P →
      P ∈ Algebra.adjoin ℝ {f : Matrix (Fin n) (Fin n) R → R | ∃ r : ℕ, f = fun A ↦ tr (A ^ r)}

Litlib.equation "nakahara2003geometry" eq "11.1" kind "theorem"
/--
Chern-Weil Theorem.
(a) The exterior derivative of the invariant polynomial applied to the curvature vanishes.
(b) The invariant polynomial applied to different curvatures differs by an exact form.
The exterior derivative `d` is constrained to be nilpotent (`d² = 0`), and exactness
is explicitly defined via an existential quantifier `∃ Q, ... = d Q`.
-/
class Theorem11_1
    (Form : Type*) [AddCommGroup Form]
    (d : Form → Form)
    (Conn : Type*)
    (F : Conn → Form)
    (P : Form → Form) where
  d_nilpotent : ∀ ω, d (d ω) = 0
  part_a : ∀ A, d (P (F A)) = 0
  part_b : ∀ A A', ∃ Q, P (F A') - P (F A) = d Q

end Litlib.Y2003.nakahara2003geometry
