-- FILENAME: Litlib/Y1969/wasserman1969equivariant/Signature.lean

import Litlib.Core
import Mathlib

Litlib.paper "wasserman1969equivariant"
  type "article"
  title "Equivariant differential topology"
  authors ["Arthur G. Wasserman"]
  journal "Topology"
  year "1969"

Litlib.equation "wasserman1969equivariant" eq "1" page "129" kind "theorem"
class EquivariantMorseBasin (G M TM : Type _) [Group G] [TopologicalSpace M] [TopologicalSpace TM]
  [MulAction G M] [MulAction G TM]
  (pi : TM → M)
  (piEquivariant : ∀ (g : G) (v : TM), pi (g • v) = g • pi v)
  (innerM : M → TM → TM → ℝ)
  (f : M → ℝ)
  (df : (M → ℝ) → M → TM → ℝ)
  (grad : (M → ℝ) → M → TM)
  (flow : (M → TM) → M → ℝ → M)
  where
  -- Garbage-in exploit prevention: require continuity of function and gradient field
  fContinuous : Continuous f
  gradContinuous : Continuous (grad f)

  -- Gradient evaluates to a section of the tangent bundle
  gradIsSection : ∀ (func : M → ℝ) (p : M), pi (grad func p) = p
  
  -- The function is G-invariant
  fInv : ∀ (g : G) (p : M), f (g • p) = f p
  
  -- The metric is G-invariant (isometry property)
  innerIsometry : ∀ (g : G) (p : M) (v w : TM), 
    pi v = p → pi w = p → 
    innerM (g • p) (g • v) (g • w) = innerM p v w
  
  -- Differential of an invariant function pulls back equivariantly
  dfPullback : ∀ (func : M → ℝ),
    (∀ (g : G) (p : M), func (g • p) = func p) →
    ∀ (g : G) (p : M) (v : TM), 
    pi v = p → 
    df func (g • p) (g • v) = df func p v
  
  -- Definition of the gradient via the Riemannian metric
  gradDef : ∀ (func : M → ℝ) (p : M) (v : TM), 
    pi v = p → 
    innerM p (grad func p) v = df func p v

  -- The Equivariance of the Gradient Field (from page 129)
  -- "g ∇f_p = ∇f_{gp} and hence ∇f is an equivariant vector field"
  gradEquivariant : ∀ (g : G) (p : M), g • grad f p = grad f (g • p)

  -- The proof expansion explicitly required by the text to prevent opaque function exploits
  -- <g ∇f_p, X> = <∇f_p, g⁻¹ X> = df_p(g⁻¹ X) = d(f g⁻¹)_{gp}(X) = df_{gp}(X) = <∇f_{gp}, X>
  gradEquivarianceProofChain : ∀ (g : G) (p : M) (X : TM),
    pi X = g • p →
    innerM (g • p) (g • grad f p) X = innerM p (grad f p) (g⁻¹ • X) ∧
    innerM p (grad f p) (g⁻¹ • X) = df f p (g⁻¹ • X) ∧
    df f p (g⁻¹ • X) = df f (g • p) X ∧
    df f (g • p) X = innerM (g • p) (grad f (g • p)) X

  -- Flow equivariance 
  -- "g σ_p(t) = σ_{gp}(t). Therefore the flow generated by X is equivariant."
  -- We pass the specific functional gradient of f to the flow generator.
  flowEquivariant : ∀ (g : G) (p : M) (t : ℝ), 
    g • flow (grad f) p t = flow (grad f) (g • p) t
