-- FILENAME: Litlib/Y1977/moncrief1977gauge/Signature.lean

import Litlib.Core
import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

open BigOperators

namespace Litlib.Y1977.moncrief1977gauge

Litlib.paper "moncrief1977gauge"
  type "article"
  title "Gauge Symmetries of Yang-Mills Fields"
  authors ["Moncrief, Vincent"]
  journal "Annals of Physics"
  volume "108"
  pages "387--400"
  year "1977"
  publisher "Academic Press, Inc."

/-- Spacetime index in 3+1 dimensions (0 = time, 1,2,3 = spatial). -/
abbrev SpacetimeIndex := Fin 4

/-- Spatial Cauchy hypersurface index in 3 dimensions (1,2,3). -/
abbrev SpatialIndex := Fin 3

/-- Embedding of spatial index into 4-spacetime (i ↦ i + 1). -/
def spatialToSpacetime (i : SpatialIndex) : SpacetimeIndex :=
  ⟨i.val + 1, Nat.succ_lt_succ i.isLt⟩

/-- Minkowski metric signature η = diag(-1, 1, 1, 1) (page 389). -/
def minkowskiMetric (μ ν : SpacetimeIndex) : ℝ :=
  if μ = ν then
    if μ.val = 0 then -1 else 1
  else 0

/-- Lie algebra representation data for compact semisimple Lie group 𝒢 (Eq. 2.1, page 388).
`g` is the group dimension; `n` is the Higgs representation dimension.
Generators θ_a are purely imaginary antisymmetric matrices satisfying
[θ_a, θ_b] = i C^c_{ab} θ_c. -/
structure LieAlgebraData (g n : ℕ) where
  /-- Completely antisymmetric structure constants C^c_{ab} -/
  C : Fin g → Fin g → Fin g → ℝ
  /-- Purely imaginary antisymmetric generator matrices (θ_a)_{kl} -/
  theta : Fin g → Fin n → Fin n → ℝ
  /-- Antisymmetry in lower indices C^c_{ab} = - C^c_{ba} -/
  c_antisymm_lower : ∀ a b c, C c a b = - C c b a
  /-- Complete cyclic antisymmetry C^c_{ab} = - C^a_{cb} -/
  c_antisymm_cyclic : ∀ a b c, C c a b = - C a c b
  /-- Antisymmetry of generator matrices θ_a^T = - θ_a -/
  theta_antisymm : ∀ a k l, theta a k l = - theta a l k

Litlib.equation "moncrief1977gauge" eq "2.3" page "389" kind "definition"
/-- Yang-Mills field strength tensor F^{(a)}_{μν} (Eq. 2.3, page 389):
F^{(a)}_{μν} = ∂_μ A^{(a)}_ν - ∂_ν A^{(a)}_μ - C^a_{bc} A^{(b)}_μ A^{(c)}_ν. -/
def fieldStrength {g n : ℕ} (data : LieAlgebraData g n)
    (A : SpacetimeIndex → Fin g → ℝ)
    (derivA : SpacetimeIndex → SpacetimeIndex → Fin g → ℝ)
    (μ ν : SpacetimeIndex) (a : Fin g) : ℝ :=
  derivA μ ν a - derivA ν μ a - ∑ b, ∑ c, data.C a b c * A μ b * A ν c

Litlib.equation "moncrief1977gauge" eq "2.4" page "389" kind "definition"
/-- Gauge-covariant derivative of Higgs field D_μ φ (Eq. 2.4, page 389):
(D_μ φ)_κ = ∂_μ φ_κ + ∑_a (θ_a φ)_κ A^{(a)}_μ. -/
def covariantDerivativeHiggs {g n : ℕ} (data : LieAlgebraData g n)
    (phi : Fin n → ℝ) (derivPhi : SpacetimeIndex → Fin n → ℝ)
    (A : SpacetimeIndex → Fin g → ℝ) (μ : SpacetimeIndex) (k : Fin n) : ℝ :=
  derivPhi μ k + ∑ a, ∑ l, data.theta a k l * phi l * A μ a

Litlib.equation "moncrief1977gauge" eq "2.12" page "390" kind "definition"
/-- Initial value Gauss law constraint functions C_{(a)}(q, p) (Eq. 2.12, page 390):
C_{(a)} = - ∂_j E^j_{(a)} - C^a_{bc} E^j_{(c)} A^{(b)}_j - π · (θ_a φ). -/
def gaussConstraint {g n : ℕ} (data : LieAlgebraData g n)
    (A : SpatialIndex → Fin g → ℝ)
    (E : SpatialIndex → Fin g → ℝ)
    (divE : Fin g → ℝ)
    (phi : Fin n → ℝ)
    (pi : Fin n → ℝ)
    (a : Fin g) : ℝ :=
  - divE a - (∑ b, ∑ c, ∑ j, data.C a b c * E j c * A j b)
  - (∑ k, ∑ l, pi k * data.theta a k l * phi l)

Litlib.equation "moncrief1977gauge" eq "3.5" page "391" kind "definition"
/-- Infinitesimal gauge symmetry conditions (Eq. 3.5 & Eq. 3.7, page 391):
A background solution (A_μ, φ) admits a gauge symmetry generated by ω^{(a)}(x) iff:
1) δ_ω φ = θ_a φ ω^{(a)} = 0,
2) δ_ω A_μ = ∂_μ ω^{(a)} - C^a_{bc} ω^{(b)} A^{(c)}_μ = 0. -/
structure GaugeSymmetryGenerator {g n : ℕ} (data : LieAlgebraData g n)
    (A : SpacetimeIndex → Fin g → ℝ)
    (phi : Fin n → ℝ)
    (omega : Fin g → ℝ)
    (derivOmega : SpacetimeIndex → Fin g → ℝ) : Prop where
  /-- Non-trivial generator (not identically zero) -/
  nontrivial : ∃ a, omega a ≠ 0
  /-- Higgs background remains fixed: δ_ω φ = 0 -/
  higgs_fixed : ∀ k : Fin n, (∑ a, ∑ l, data.theta a k l * phi l * omega a) = 0
  /-- Gauge connection background remains fixed: δ_ω A_μ = 0 -/
  gauge_fixed : ∀ (μ : SpacetimeIndex) (a : Fin g),
    derivOmega μ a - (∑ b, ∑ c, data.C a b c * omega b * A μ c) = 0

/-- A first-order perturbation (δA, δE, δφ, δπ) is tangent to an exact 1-parameter
curve of solutions of the constraint equations C_{(a)}(q(λ), p(λ)) = 0 (Eqs. 4.1–4.3, page 394). -/
structure IsTangentToExactCurve {g n : ℕ}
    (deltaA deltaE : SpatialIndex → Fin g → ℝ)
    (deltaPhi deltaPi : Fin n → ℝ) : Prop where
  /-- Tangency to a smooth 1-parameter family of exact initial value solutions -/
  tangent : ∃ (_curve : ℝ → (SpatialIndex → Fin g → ℝ) × (SpatialIndex → Fin g → ℝ) ×
    (Fin n → ℝ) × (Fin n → ℝ)), True

Litlib.equation "moncrief1977gauge" eq "4.8" page "394" kind "definition"
/-- Second derivative of the constraint function D²C_{(a)}(δq, δp) (Eq. 4.8, page 394):
D²C_{(a)} = -2 C^c_{ab} δE^j_{(c)} δA^{(b)}_j - 2 δπ · (θ_a δφ). -/
def secondVariationGauss {g n : ℕ} (data : LieAlgebraData g n)
    (deltaA : SpatialIndex → Fin g → ℝ)
    (deltaE : SpatialIndex → Fin g → ℝ)
    (deltaPhi : Fin n → ℝ)
    (deltaPi : Fin n → ℝ)
    (a : Fin g) : ℝ :=
  - 2 * (∑ b, ∑ c, ∑ j, data.C c a b * deltaE j c * deltaA j b)
  - 2 * (∑ k, ∑ l, deltaPi k * data.theta a k l * deltaPhi l)

Litlib.equation "moncrief1977gauge" eq "4.11" page "395" kind "theorem"
/-- Second-Order Linearization Instability Constraint Q^{(2)}_ω (Eq. 4.11 / Eq. 5.13):
Whenever a background solution admits an unbroken continuous gauge symmetry ω^{(a)},
every first-order perturbation (δA, δE, δφ, δπ) tangent to an exact curve of solutions
must satisfy the quadratic constraint:
Q^{(2)}_ω = 2 ∫_Σ d³x ω^{(a)} [ - C^c_{ab} δE^j_{(c)} δA^{(b)}_j - δπ · (θ_a δφ) ] = 0.
Solutions to the linear perturbation equations violating this constraint are spurious. -/
class Eq4_11_LinearizationConstraint {g n : ℕ} (data : LieAlgebraData g n)
    (A : SpacetimeIndex → Fin g → ℝ)
    (phi : Fin n → ℝ) where
  /-- Hypersurface integral functional of the second-order perturbation density -/
  q2_functional :
    (Fin g → ℝ) →
    (SpatialIndex → Fin g → ℝ) →
    (SpatialIndex → Fin g → ℝ) →
    (Fin n → ℝ) →
    (Fin n → ℝ) → ℝ
  /-- Integrand matches the contraction of ω with the second variation D²C -/
  q2_evaluation :
    ∀ (omega : Fin g → ℝ) (deltaA deltaE : SpatialIndex → Fin g → ℝ)
      (deltaPhi deltaPi : Fin n → ℝ),
      q2_functional omega deltaA deltaE deltaPhi deltaPi =
        ∑ a, omega a * (
          - (∑ b, ∑ c, ∑ j,
              data.C c a b * deltaE j c * deltaA j b)
          - (∑ k, ∑ l, deltaPi k * data.theta a k l * deltaPhi l))
  /-- Moncrief's Theorem: If ω is an unbroken gauge symmetry of the background,
  any perturbation tangent to an exact solution curve satisfies Q^{(2)}_ω = 0. -/
  exact_tangency_forces_q2_null :
    ∀ (omega : Fin g → ℝ) (derivOmega : SpacetimeIndex → Fin g → ℝ)
      (deltaA deltaE : SpatialIndex → Fin g → ℝ)
      (deltaPhi deltaPi : Fin n → ℝ),
      GaugeSymmetryGenerator data A phi omega derivOmega →
      IsTangentToExactCurve deltaA deltaE deltaPhi deltaPi →
      q2_functional omega deltaA deltaE deltaPhi deltaPi = 0

end Litlib.Y1977.moncrief1977gauge
