-- FILENAME: Litlib/Y1994/sorkin1994quantum/Signature.lean

import Litlib.Core
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

open BigOperators

namespace Litlib.Y1994.sorkin1994quantum

Litlib.paper "sorkin1994quantum"
  type "article"
  title "Quantum Mechanics as Quantum Measure Theory"
  authors ["Sorkin, Rafael D."]
  journal "Modern Physics Letters A"
  volume "9"
  issue "33"
  pages "3119--3127"
  year "1994"
  doi "10.1142/S021773239400294X"

/-- Single-alternative measure I₁(A) ≡ |A| (page 3120). -/
def interference1 (μ : Finset α → ℝ) (A : Finset α) : ℝ :=
  μ A

/-- Two-slit interference functional I₂(A, B) ≡ |A ⊔ B| - |A| - |B| (page 3120).
In classical probability theory, I₂ vanishes identically on disjoint events. -/
def interference2 [DecidableEq α] (μ : Finset α → ℝ) (A B : Finset α) : ℝ :=
  μ (A ∪ B) - μ A - μ B

/-- Three-slit interference functional I₃(A, B, C) (Eq. 1 / Eq. 2, page 3120-3121).
I₃(A, B, C) = |A ⊔ B ⊔ C| - |A ⊔ B| - |B ⊔ C| - |A ⊔ C| + |A| + |B| + |C|. -/
def interference3 [DecidableEq α] (μ : Finset α → ℝ) (A B C : Finset α) : ℝ :=
  μ (A ∪ B ∪ C) - (μ (A ∪ B) + μ (B ∪ C) + μ (A ∪ C)) + (μ A + μ B + μ C)

/-- Generalized bilateral interference extension I(A, B) to arbitrary (possibly overlapping)
subsets preserving bi-additivity (Eq. 5, page 3122):
I(A, B) = |A ∪ B| + |A ∩ B| - |A \ B| - |B \ A|. -/
def extendedInterference [DecidableEq α] (μ : Finset α → ℝ) (A B : Finset α) : ℝ :=
  μ (A ∪ B) + μ (A ∩ B) - μ (A \ B) - μ (B \ A)

/-- Equivalent symmetric difference form of extended bilateral interference (page 3122):
I(A, B) = |A Δ B| + |A| + |B| - 2|A \ B| - 2|B \ A|. -/
def extendedInterferenceSymmDiff [DecidableEq α] (μ : Finset α → ℝ) (A B : Finset α) : ℝ :=
  μ ((A \ B) ∪ (B \ A)) + μ A + μ B - 2 * μ (A \ B) - 2 * μ (B \ A)

/-- Quantum measure generated by a complex path amplitude field ψ via the Born rule.
The probability of a bundle of histories S is the squared modulus of the coherent
amplitude sum (page 3123): μ(S) = |∑_{x ∈ S} ψ(x)|². -/
def bornMeasure (ψ : α → ℂ) (S : Finset α) : ℝ :=
  Complex.normSq (∑ x ∈ S, ψ x)

Litlib.equation "sorkin1994quantum" eq "Lemma" page "3121" kind "theorem"
/-- Inductive recursion lemma relating consecutive orders of the interference hierarchy:
I_{n+1}(A₀, A₁, ..., Aₙ) = Iₙ(A₀ ⊔ A₁, A₂, ...) - Iₙ(A₀, A₂, ...) - Iₙ(A₁, A₂, ...).
Specifically, I₃(A, B, C) = I₂(A ⊔ B, C) - I₂(A, C) - I₂(B, C). -/
class Lemma_InductiveRelation (α : Type*) [DecidableEq α] where
  /-- Third-order interference expresses the failure of I₂ to be additive in its first argument -/
  i3_as_i2_difference :
    ∀ (μ : Finset α → ℝ) (A B C : Finset α),
      Disjoint A B → Disjoint (A ∪ B) C →
      interference3 μ A B C =
        interference2 μ (A ∪ B) C - interference2 μ A C - interference2 μ B C

Litlib.equation "sorkin1994quantum" eq "2" page "3121" kind "definition"
/-- Sorkin's Grade-2 Quantum Measure Sum-Rule (Eq. 2, page 3121):
|A ⊔ B ⊔ C| - |A ⊔ B| - |B ⊔ C| - |A ⊔ C| + |A| + |B| + |C| = 0.
Defines quantum mechanics as the exact stage in the hierarchy where I₂ ≠ 0 but I₃ ≡ 0. -/
class Eq2_QuantumMeasureSumRule (α : Type*) [DecidableEq α] where
  /-- The underlying quantum measure functional -/
  measure : Finset α → ℝ
  /-- Non-negativity of event probabilities -/
  nonneg : ∀ S, 0 ≤ measure S
  /-- Empty history carries zero measure -/
  empty_null : measure ∅ = 0
  /-- Identical vanishing of the 3-slit interference term for mutually disjoint alternatives -/
  sum_rule :
    ∀ (A B C : Finset α),
      Disjoint A B → Disjoint B C → Disjoint A C →
      interference3 measure A B C = 0

Litlib.equation "sorkin1994quantum" eq "3" page "3122" kind "theorem"
/-- Bi-additivity of two-slit interference under the quantum sum-rule (Eq. 3, page 3122):
I(A ⊔ B, C) = I(A, C) + I(B, C) for mutually disjoint A, B, C. -/
class Eq3_Biadditivity (α : Type*) [DecidableEq α] where
  /-- I₂ is additive in its arguments when the grade-2 sum-rule holds -/
  biadditive :
    ∀ (μ : Finset α → ℝ),
      (∀ A B C : Finset α, Disjoint A B → Disjoint B C → Disjoint A C →
        interference3 μ A B C = 0) →
      ∀ A B C : Finset α, Disjoint A B → Disjoint (A ∪ B) C →
        interference2 μ (A ∪ B) C = interference2 μ A C + interference2 μ B C

Litlib.equation "sorkin1994quantum" eq "4" page "3122" kind "theorem"
/-- Diagonal identification of bilateral interference with the measure (Eq. 4, page 3122):
I(X, X) = 2 |X|. -/
class Eq4_DiagonalIdentification (α : Type*) [DecidableEq α] where
  /-- Evaluation of bilateral interference on identical arguments yields twice the measure -/
  diagonal_eq_two_measure :
    ∀ (μ : Finset α → ℝ) (X : Finset α),
      μ ∅ = 0 → extendedInterference μ X X = 2 * μ X

Litlib.equation "sorkin1994quantum" eq "BornNullityTheorem" page "3123" kind "theorem"
/-- Main Theorem: The standard Born rule probability rule μ(S) = |∑_{x ∈ S} ψ(x)|²
identically satisfies Sorkin's 3-slit interference nullity condition I₃(A, B, C) ≡ 0. -/
class Eq2_ThirdOrderInterferenceNullity (α : Type*) [DecidableEq α] where
  /-- Third-order interference identically vanishes for disjoint beam paths under the Born rule -/
  born_measure_i3_null :
    ∀ (ψ : α → ℂ) (A B C : Finset α),
      Disjoint A B → Disjoint B C → Disjoint A C →
      interference3 (bornMeasure ψ) A B C = 0

end Litlib.Y1994.sorkin1994quantum
