-- FILENAME: Litlib/Y1946/weyl1946classical/Signature.lean

import Litlib.Core
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.Module.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.RepresentationTheory.Maschke
import Mathlib.Data.Complex.Basic
import Mathlib.Algebra.Algebra.IsSimpleRing
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic

open Matrix BigOperators

namespace Litlib.Y1946.weyl1946classical

Litlib.paper "weyl1946classical"
  type "book"
  title "The classical groups: their invariants and representations"
  authors ["Weyl, Hermann"]
  volume "1"
  year "1946"
  publisher "Princeton university press"

Litlib.equation "weyl1946classical"
  eq "3.1.A"
  page "81"
  kind "Lemma"
class Lemma3_1_A where
  /-- 
  Physical Interpretation & Mathematical Boundaries:
  Schur's Lemma for representations of algebras. In quantum mechanics and gauge theory, 
  this foundational lemma guarantees that any operator that commutes with all observables 
  of an irreducible representation space must either be identically zero or strictly invertible. 
  Over an algebraically closed field, this forces such operators to be scalar multiples 
  of the identity, rigorously enforcing superselection rules and determining the structure 
  of the system's commutator algebra.
  
  Relationship to Literature:
  Formalizes Chapter III, Lemma 3.1.A of Weyl's "The Classical Groups": "If L is irreducible 
  in k, then any commutator A of L in k is either zero or non-singular; in other words, 
  the commutator algebra A of L in k is a division algebra."
  -/
  endOfSimpleModuleIsDivisionRing (R V : Type*) [Ring R] [AddCommGroup V] [Module R V] [IsSimpleModule R V] : 
    ∀ (f : Module.End R V), f ≠ 0 → IsUnit f

Litlib.equation "weyl1946classical"
  eq "3.3.A"
  page "87"
  kind "Theorem"
class Thm3_3_A where
  /-- 
  Physical Interpretation & Mathematical Boundaries:
  Demonstrates that a division algebra possesses no non-trivial two-sided ideals, rendering 
  its regular representation strictly simple. Physically, this classifies the underlying 
  algebraic structures of observables (e.g., the field of real numbers or the algebra of 
  quaternions) as indivisible, atomic symmetry domains without proper invariant sub-sectors.
  
  Relationship to Literature:
  Directly formalizes Chapter III, Theorem 3.3.A of Weyl: "A division algebra a is simple."
  -/
  divisionRingIsSimpleRing (D : Type*) [DivisionRing D] : IsSimpleRing D

Litlib.equation "weyl1946classical"
  eq "3.7.A"
  page "101"
  kind "Theorem"
class Thm3_7_A where
  /-- 
  Physical Interpretation & Mathematical Boundaries:
  Maschke's Theorem for the regular representation. In the context of quantum mechanics, 
  this theorem guarantees that any state space transforming under a finite symmetry group 
  (such as a lattice point group) can be fully decomposed into a direct sum of independent, 
  irreducible symmetry modes. 
  
  Algebraic Non-Degeneracy Constraint:
  The theorem explicitly requires that the order of the group `G` is invertible in the 
  underlying field `k` (`Invertible (Fintype.card G : k)`). This prevents the "modular" 
  collapse of the representation theory, which would otherwise allow non-diagonalizable 
  (indecomposable but reducible) physical states.
  
  Relationship to Literature:
  Formalizes Chapter III, Section 7, Theorem 3.7.A of Weyl, which asserts that every 
  invariant subspace of the group ring possesses an idempotent generator, an algebraic 
  condition equivalent to the semisimplicity of the group ring.
  -/
  groupRingIsSemisimple (k G : Type*) [Field k] [Group G] [Fintype G] [Invertible (Fintype.card G : k)] :
    IsSemisimpleRing (MonoidAlgebra k G)

Litlib.equation "weyl1946classical"
  eq "8.6.A"
  page "251"
  kind "Theorem"
class Thm8_6_A where
  /-- 
  Physical Interpretation & Mathematical Boundaries:
  Hilbert's Basis Theorem. Asserts that the ring of polynomials over a Noetherian 
  ring is itself Noetherian. In the context of invariant theory and theoretical physics, 
  this provides the foundational guarantee that any infinite set of polynomial invariants 
  (e.g., physical observables constructed from tensorial quantities) can be generated by 
  a finite basis. This precludes the pathological necessity of requiring an infinite number 
  of fundamental observables to describe the state of a physical system.
  
  Relationship to Literature:
  Formalizes Chapter VIII, Theorem 8.6.A of Weyl: "If every ideal in the ring R has 
  a finite ideal basis then the same is true for the ring R[x]."
  -/
  polynomialIsNoetherian (R : Type*) [CommRing R] [IsNoetherianRing R] : 
    IsNoetherianRing (Polynomial R)

Litlib.equation "weyl1946classical"
  eq "2.9.A (Corollary)"
  page "53"
  kind "Corollary"
class PhysicsCorollary2_9_A_Rank4 where
  /-- 
  Physical Interpretation & Mathematical Boundaries:
  Classification of rank-4 invariant tensors under the proper complex orthogonal group SO(4, ℂ).
  In relativistic field theories (e.g., Euclideanized quantum gravity or Yang-Mills theories), 
  any interaction vertex, effective action term, or correlation function of rank 4 that is 
  locally Lorentz invariant must be constructible purely from the metric tensor `eta` and 
  the fully antisymmetric Levi-Civita volume form `epsilon4`. 
  
  Geometric Non-Degeneracy Constraint:
  The macroscopic metric determinant is strictly required to be non-zero (`Matrix.det eta ≠ 0`) 
  to prevent the topological collapse of the spacetime volume form. Furthermore, the alternating 
  tensor `epsilon4` must not be identically zero.
  
  Relationship to Literature:
  This corollary explicitly implements Chapter II, Theorem 2.9.A of Weyl, which states that 
  every even orthogonal invariant is expressible via combinations of the scalar product, and 
  every odd invariant is proportional to the bracket factor (the volume form). For rank 4 in 
  4 dimensions, this yields exactly three metric pairings and one volume form.
  -/
  uniqueLorentzInvariantRank4 
    (eta : Matrix (Fin 4) (Fin 4) ℂ)
    (epsilon4 : Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℂ)
    (T : Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℂ)
    (hEtaSymm : ∀ i j, eta i j = eta j i)
    (hEtaNondeg : Matrix.det eta ≠ 0)
    (hEpsilonAlt : ∀ α β γ δ, 
      epsilon4 α β γ δ = -epsilon4 β α γ δ ∧ 
      epsilon4 α β γ δ = -epsilon4 α γ β δ ∧ 
      epsilon4 α β γ δ = -epsilon4 α β δ γ)
    (hEpsilonNondeg : epsilon4 0 1 2 3 ≠ 0)
    (hInv : ∀ (Λ : Matrix (Fin 4) (Fin 4) ℂ),
      Λ * eta * Matrix.transpose Λ = eta → Matrix.det Λ = 1 →
      ∀ μ ν ρ σ, ∑ α : Fin 4, ∑ β : Fin 4, ∑ γ : Fin 4, ∑ δ : Fin 4,
        Λ μ α * Λ ν β * Λ ρ γ * Λ σ δ * T α β γ δ = T μ ν ρ σ) :
    ∃ (c1 c2 c3 c4 : ℂ), ∀ μ ν ρ σ,
      T μ ν ρ σ = c1 * (eta μ ν * eta ρ σ) + c2 * (eta μ ρ * eta ν σ) + c3 * (eta μ σ * eta ν ρ) + c4 * epsilon4 μ ν ρ σ

end Litlib.Y1946.weyl1946classical
