-- FILENAME: Litlib/Y1946/weyl1946classical/Chapter08/Sec06_HilbertBasis.lean

import Mathlib
import Litlib.Core

namespace Litlib.Y1946.weyl1946classical

Litlib.equation "weyl1946classical" eq "8.6.A" page "251" kind "Theorem"
class Thm8_6_A where
  /--
  Physical Interpretation & Mathematical Boundaries:
  Hilbert's Basis Theorem. Asserts that the ring of polynomials over a Noetherian
  ring is itself Noetherian. In the context of invariant theory and theoretical physics,
  this provides the foundational guarantee that any infinite set of polynomial invariants
  (e.g., physical observables constructed from tensorial quantities) can be generated by
  a finite basis. This precludes the pathological necessity of requiring an infinite number
  of fundamental observables to describe the state of a physical system.

  Relationship to Literature:
  Formalizes Chapter VIII, Theorem 8.6.A of Weyl: "If every ideal in the ring R has
  a finite ideal basis then the same is true for the ring R[x]."
  -/
  polynomialIsNoetherian (R : Type*) [CommRing R] [IsNoetherianRing R] :
    IsNoetherianRing (Polynomial R)
