-- FILENAME: Litlib/Core/CLI/Latex.lean

import Lean

open Lean

namespace Litlib.Core.CLI

def escapeLatex (s : String) : String :=
  s.replace "_" "\\_"

def injectLabelsAndLinks (code : String) (declName : Name) (nameMap : Array (String × Name)) (isLatex : Bool) : String := Id.run do
  if !isLatex then return code
  
  let chars := code.toList.toArray
  let mut out := ""
  let mut i := 0
  let mut inString := false
  let mut inLineComment := false
  let mut blockCommentDepth := 0
  
  let mut firstIdentReplaced := false
  let shortName := declName.getString!
  
  let mut citeStr := ""
  let nameParts := declName.toString.splitOn "."
  if nameParts.length >= 3 && nameParts[0]! == "Litlib" && nameParts[1]!.startsWith "Y" then
    let bibKey := nameParts[2]!
    citeStr := "§\\textsuperscript{\\pdftooltip{\\cite{" ++ bibKey ++ "}}{Reference: " ++ bibKey ++ "}}§"
  
  while i < chars.size do
    let c := chars[i]!
    let nextC := if i + 1 < chars.size then chars[i+1]! else ' '
    
    if inLineComment then
      out := out.push c
      if c == '\n' then inLineComment := false
      i := i + 1
      continue
      
    if blockCommentDepth > 0 then
      out := out.push c
      if c == '/' && nextC == '-' then
        blockCommentDepth := blockCommentDepth + 1
        out := out.push nextC
        i := i + 2
        continue
      else if c == '-' && nextC == '/' then
        blockCommentDepth := blockCommentDepth - 1
        out := out.push nextC
        i := i + 2
        continue
      i := i + 1
      continue
      
    if inString then
      out := out.push c
      if c == '"' && (i == 0 || chars[i-1]! != '\\') then
        inString := false
      i := i + 1
      continue
      
    if c == '"' then
      inString := true
      out := out.push c
      i := i + 1
      continue
    if c == '-' && nextC == '-' then
      inLineComment := true
      out := out.push c
      out := out.push nextC
      i := i + 2
      continue
    if c == '/' && nextC == '-' then
      blockCommentDepth := 1
      out := out.push c
      out := out.push nextC
      i := i + 2
      continue
      
    if c.isAlpha || c == '_' then
      let mut identChars := ""
      while i < chars.size do
        let ic := chars[i]!
        if ic.isAlphanum || ic == '_' || ic == '.' || ic == '\'' then
          identChars := identChars.push ic
          i := i + 1
        else
          break
      
      if !firstIdentReplaced && identChars == shortName then
        -- Close the escape around the label, let minted print the name normally, then inject the citeStr
        out := out ++ "§\\phantomsection\\label{lean:" ++ declName.toString ++ "}§" ++ declName.toString ++ citeStr
        firstIdentReplaced := true
      else if let some (_, linkedName) := nameMap.find? (fun (k, _) => k == identChars) then
        if linkedName == declName then
          out := out ++ identChars
        else
          -- Provide the explicit hyperlink, detokenizing the visual text to protect against underscores
          out := out ++ "§\\hyperref[lean:" ++ linkedName.toString ++ "]{\\detokenize{" ++ identChars ++ "}}§"
      else
        out := out ++ identChars
        
      continue
      
    out := out.push c
    i := i + 1
    
  if !firstIdentReplaced then
    return "§\\phantomsection\\label{lean:" ++ declName.toString ++ "}§" ++ out
    
  return out

def generateLitlibSty (dir : System.FilePath) : IO Unit := do
  let content := "% litlib.sty - Generated by litlib4
\\ProvidesPackage{litlib}[2024/01/01 Litlib LaTeX support]

\\RequirePackage{hyperref}
\\RequirePackage{pdfcomment}
\\RequirePackage{minted}
\\RequirePackage{xcolor}

\\setminted{
    linenos=true,
    breaklines=true,
    breakanywhere=true,
    frame=lines,
    framesep=2mm,
    fontsize=\\footnotesize,
    bgcolor=gray!5,
    escapeinside=§§
}

\\newcounter{leancnt}
\\newwrite\\leanfile

\\AtBeginDocument{%
    \\immediate\\openout\\leanfile=\\jobname.leanrefs
    \\immediate\\write\\leanfile{\\string\\relax}
}

\\makeatletter
\\newcommand{\\leanref}[1]{%
    \\ifmeasuring@
        \\ifmmode {}^{\\textnormal{[L?]}} \\else \\textsuperscript{[L?]} \\fi
    \\else
        \\expandafter\\ifx\\csname lean@ref@id@\\detokenize{#1}\\endcsname\\relax
            \\stepcounter{leancnt}%
            \\expandafter\\xdef\\csname lean@ref@id@\\detokenize{#1}\\endcsname{\\theleancnt}%
            \\immediate\\write\\leanfile{%
                \\string\\noindent\\string\\textbf{[L\\theleancnt]}\\string\\quad%
                \\string\\hyperref[lean:#1]{\\string\\texttt{\\string\\detokenize{#1}}}%
                \\string\\dotfill\\space Line \\string\\ref{lean:#1}\\string\\par\\string\\vspace{0.5em}%
            }%
        \\fi
        \\ifmmode 
            {}^{\\textnormal{\\hyperref[lean:#1]{[L\\csname lean@ref@id@\\detokenize{#1}\\endcsname]}}}%
        \\else 
            \\textsuperscript{\\hyperref[lean:#1]{\\pdftooltip{[L\\csname lean@ref@id@\\detokenize{#1}\\endcsname]}{\\detokenize{#1}}}}%
        \\fi
    \\fi
}
\\makeatother

\\newcommand{\\aleanref}[1]{\\rlap{\\quad \\leanref{#1}}}

\\newcommand{\\printleanrefs}{%
    \\section*{Formal Verification Index}%
    \\noindent The equations annotated with \\textbf{[L$n$]} in the main text have been formally verified in Lean 4. Click the theorem name to jump to the code signature, or reference the line number in the Appendix.
    \\par\\vspace{1em}
    \\immediate\\closeout\\leanfile
    \\input{\\jobname.leanrefs}
}
"
  IO.FS.writeFile (dir / "litlib.sty") content

def generateLatexReadme (dir : System.FilePath) : IO Unit := do
  let content := "# Litlib LaTeX Artifacts

This directory contains automatically generated files to seamlessly integrate your formal Lean 4 verification into your LaTeX paper.

## 1. Setup

If you generated this inside your `paper/` directory, the files are already in place! 

In your LaTeX preamble, include the `litlib` package:
```latex
\\usepackage{litlib}
```
*(Note: `litlib.sty` automatically loads `minted`, `hyperref`, and `xcolor`.)*

## 2. Bibliography

You do **not** need to manually copy and paste the generated citations into your hand-crafted `.bib` file! LaTeX perfectly supports multiple bibliography sources.

**If using BibLaTeX:**
```latex
\\addbibresource{my-references.bib}
\\addbibresource{litlib-references.bib}
```

**If using traditional BibTeX:**
```latex
\\bibliography{my-references,litlib-references}
```

**Smart Deduplication:** 
`litlib4` automatically scans your target directory for any existing `.bib` files (e.g. your manual bibliography database). If it finds that you have already defined a specific BibTeX key manually, it will gracefully suppress that key from `litlib-references.bib` so that BibLaTeX/BibTeX will never complain about duplicate definitions!

## 3. The Code Summary Appendix

To embed the fully formatted and automatically hyperlinked Lean code summary into your paper, simply input the `.tex` file under a section or appendix heading:
```latex
\\section{Formal Code Summary}
\\label{sec:code_summary}
\\input{litlib-code-summary.tex}
```

**Speeding up LaTeX compilation:**
Because `minted` shells out to Pygments to format the syntax highlighting, compiling the full code summary can significantly slow down your build times while drafting. To do a fast build, simply comment out the `\\input` line:
```latex
% \\input{litlib-code-summary.tex}
```
The `\\leanref` citations in your main text will still work and print the appropriate `[L?]` markers, but the code block itself will be omitted until you are ready for a final build.

## 4. Inline Citations

Inside your text, you can cite any formally verified equation or theorem by passing its exact Lean 4 declaration name to the `\\leanref` macro:
```latex
We define the Spacetime Point \\leanref{Litlib.Y2024.Author.SpacetimePoint} as...
```
This will automatically generate a clickable `[L?]` annotation in the PDF that links directly to the code summary, and logs it in the Formal Verification Index.
"
  IO.FS.writeFile (dir / "litlib-README.md") content

end Litlib.Core.CLI
