-- FILENAME: Litlib/Y2000/hall2000elementary/Signature.lean

import Litlib.Core
import Mathlib.Data.Complex.Basic
import Mathlib.Topology.Basic
import Mathlib.Order.Filter.Basic
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Analysis.Matrix.Normed

open Filter Topology BigOperators

namespace Litlib.Y2000.hall2000elementary

Litlib.paper "hall2000elementary"
  type "article"
  title "An elementary introduction to groups and representations"
  authors ["Hall, Brian C."]
  journal "arXiv preprint math-ph/0005032"
  year "2000"
  doi "10.48550/arXiv.math-ph/0005032"

Litlib.equation "hall2000elementary"
  eq "Prop 3.3"
  page "28"
  kind "Proposition"
class CommutingExponential 
    (n : Type*) [Fintype n] [DecidableEq n]
    (exp : Matrix n n ℂ → Matrix n n ℂ) where
  hIsExp : ∀ X, Tendsto (fun m : ℕ => ∑ k ∈ Finset.range m, (1 / (Nat.factorial k : ℂ)) • X^k) atTop (𝓝 (exp X))
  
  /--
  # Proposition: Commuting Exponential
  **Literature:** Hall 2000, Proposition 3.3, Page 28.
  **Physical Interpretation:** In the algebra of quantum observables or state transformations, the time evolution generated by a sum of two Hamiltonians $X$ and $Y$ factorizes into sequential evolutions $e^X e^Y$ if and only if the generators strictly commute. This encapsulates the fundamental difference between abelian and non-abelian Lie group dynamics.
  **Mathematical Boundaries:** Relies on the absolute convergence of the matrix exponential series. The explicit algebraic assumption `X * Y = Y * X` ensures the Lie bracket vanishes, enabling the factorization.
  -/
  commutingExp :
    ∀ X Y : Matrix n n ℂ, X * Y = Y * X → exp (X + Y) = exp X * exp Y

Litlib.equation "hall2000elementary"
  eq "Prop 3.4"
  page "29"
  kind "Proposition"
class DerivativeExponential 
    (n : Type*) [Fintype n] [DecidableEq n]
    [NormedAddCommGroup (Matrix n n ℂ)] [NormedSpace ℝ (Matrix n n ℂ)]
    (exp : Matrix n n ℂ → Matrix n n ℂ) where
  hIsExp : ∀ X, Tendsto (fun m : ℕ => ∑ k ∈ Finset.range m, (1 / (Nat.factorial k : ℂ)) • X^k) atTop (𝓝 (exp X))
  smooth_exp : 
    ∀ X : Matrix n n ℂ, ContDiff ℝ ⊤ (fun (t : ℝ) => exp ((t : ℂ) • X))
    
  /--
  # Proposition: Derivative of the Exponential Mapping
  **Literature:** Hall 2000, Proposition 3.4, Page 29.
  **Physical Interpretation:** The matrix exponential maps a tangent vector (Lie algebra generator) to a continuous path in the Lie group. The temporal derivative of this path evaluated at the identity uniquely recovers the generator $X$. This ensures the rigorous binding between macroscopic group transformations and infinitesimal generators.
  **Mathematical Boundaries:** Enforces that the mapping from $\mathbb{R}$ to the space of matrices is smooth (`ContDiff`). The derivative applies strictly under the scalar action of the real line.
  -/
  deriv_exp : 
    ∀ (X : Matrix n n ℂ) (t : ℝ), 
      deriv (fun (s : ℝ) => exp ((s : ℂ) • X)) t = X * exp ((t : ℂ) • X) ∧ 
      deriv (fun (s : ℝ) => exp ((s : ℂ) • X)) t = exp ((t : ℂ) • X) * X
      
  deriv_exp_zero : 
    ∀ X : Matrix n n ℂ, deriv (fun (s : ℝ) => exp ((s : ℂ) • X)) 0 = X

Litlib.equation "hall2000elementary"
  eq "Thm 3.9"
  page "34"
  kind "Theorem"
class LieProductFormula 
    (n : Type*) [Fintype n] [DecidableEq n]
    (exp : Matrix n n ℂ → Matrix n n ℂ) where
  hIsExp : ∀ X, Tendsto (fun m : ℕ => ∑ k ∈ Finset.range m, (1 / (Nat.factorial k : ℂ)) • X^k) atTop (𝓝 (exp X))
  
  /--
  # Theorem: Lie Product Formula (Trotter Product)
  **Literature:** Hall 2000, Theorem 3.9, Page 34.
  **Physical Interpretation:** For non-commuting generators, macroscopic state evolution $e^{X+Y}$ can be recovered by taking the infinite limit of rapidly alternating infinitesimal evolutions of $X$ and $Y$. This is the foundational mathematics behind the path-integral formulation of quantum mechanics.
  **Mathematical Boundaries:** The sequence convergence requires topological completeness. To strictly prevent division-by-zero vulnerabilities in the formal sequence definition, the fractional parameter is strictly parameterized as `(m + 1 : ℂ)`.
  -/
  lieProductFormula :
    ∀ X Y : Matrix n n ℂ, 
      Tendsto (fun m : ℕ => (exp ((1 / ((m + 1) : ℂ)) • X) * exp ((1 / ((m + 1) : ℂ)) • Y)) ^ (m + 1)) atTop (𝓝 (exp (X + Y)))

Litlib.equation "hall2000elementary"
  eq "Thm 3.10"
  page "34"
  kind "Theorem"
class DeterminantExponential 
    (n : Type*) [Fintype n] [DecidableEq n]
    (exp : Matrix n n ℂ → Matrix n n ℂ) where
  hIsExp : ∀ X, Tendsto (fun m : ℕ => ∑ k ∈ Finset.range m, (1 / (Nat.factorial k : ℂ)) • X^k) atTop (𝓝 (exp X))
  
  /--
  # Theorem: Determinant of Exponential (Liouville's Formula)
  **Literature:** Hall 2000, Theorem 3.10, Page 34.
  **Physical Interpretation:** This theorem provides the exact algebraic mapping between the trace of a Lie algebra generator (encoding local volume expansion/contraction rates) and the determinant of the resulting Lie group transformation (encoding the macroscopic volume change). 
  **Mathematical Boundaries:** It enforces that trace-free generators (e.g., in $\mathfrak{sl}(n, \mathbb{C})$) exponentiate strictly to volume-preserving transformations (i.e., matrices with determinant 1).
  -/
  detExp :
    ∀ X : Matrix n n ℂ, Matrix.det (exp X) = Complex.exp (Matrix.trace X)

Litlib.equation "hall2000elementary"
  eq "Thm 3.12"
  page "35"
  kind "Theorem"
class OneParameterSubgroups 
    (n : Type*) [Fintype n] [DecidableEq n]
    (exp : Matrix n n ℂ → Matrix n n ℂ) where
  hIsExp : ∀ X, Tendsto (fun m : ℕ => ∑ k ∈ Finset.range m, (1 / (Nat.factorial k : ℂ)) • X^k) atTop (𝓝 (exp X))
  
  /--
  # Theorem: One-Parameter Subgroups
  **Literature:** Hall 2000, Theorem 3.12, Page 35.
  **Physical Interpretation:** Any steady, continuous time-evolution in a linear state space (forming a continuous group homomorphism from the real line $\mathbb{R}$) is governed by a single, unique constant Hamiltonian/generator.
  **Mathematical Boundaries:** The continuity of the map $A : \mathbb{R} \to GL(n, \mathbb{C})$ is strictly enforced. The structural constraints $A(0) = 1$ and $A(t+s) = A(t)A(s)$ mathematically guarantee that the image resides entirely within the invertible general linear group.
  -/
  oneParameterSubgroup :
    ∀ (A : ℝ → Matrix n n ℂ), 
      Continuous A → 
      A 0 = 1 → 
      (∀ t s : ℝ, A (t + s) = A t * A s) → 
      ∃! X : Matrix n n ℂ, ∀ t : ℝ, A t = exp ((t : ℂ) • X)

end Litlib.Y2000.hall2000elementary
